### ISSUE TITLE
UV Shape need update

### ISSUE THREAD

**Issue by brothermechanic** [the3dadvantage/Modeling-Cloth#20]
Hello
I use this great addon on blender 2.79 very well,
but on blender 2.79.4 get this error
```
Traceback (most recent call last):
  File "/home/bm/.config/blender/2.79/scripts/addons/UVShape.py", line 395, in execute
    create_uv_shape()
  File "/home/bm/.config/blender/2.79/scripts/addons/UVShape.py", line 341, in create_uv_shape
    uv_to_shape_key()
  File "/home/bm/.config/blender/2.79/scripts/addons/UVShape.py", line 238, in uv_to_shape_key
    divide_garment(ob, dict)
  File "/home/bm/.config/blender/2.79/scripts/addons/UVShape.py", line 210, in divide_garment
    linked = find_linked(ob, vert, v_list)
  File "/home/bm/.config/blender/2.79/scripts/addons/UVShape.py", line 189, in find_linked
    vert = new_verts[-cull]
TypeError: The numpy boolean negative, the `-` operator, is not supported, use the `~` operator or the logical_not function instead.

location: <unknown location>:-1
```
Please, update it.
Thank you for this super addon!

**Comment by the3dadvantage** [comment]
Should be fixed. Give it a try and let me know if you have any problems.
Thanks!
