### ISSUE TITLE
Create Pins causing error on 2.79

### ISSUE THREAD

**Issue by robw001** [the3dadvantage/Modeling-Cloth#3]
I'm using Blender 2.79 on MacOs.

As per you demo on youtube, I created a cube, subdivided it went back to Object mode, marked it Modeling Cloth and hit Play. When setting Inflate to a positive value, the cube inflates.

So far, everything works fine.

When I click Create Pins, I get an error:

```
Traceback (most recent call last):
  File "/Users/robw/Library/Application Support/Blender/2.79/scripts/addons/Modeling-Cloth-master/ModelingCloth.py", line 921, in modal
    pos = queryMousePosition()
NameError: name 'queryMousePosition' is not defined

location: <unknown location>:-1

Traceback (most recent call last):
  File "/Users/robw/Library/Application Support/Blender/2.79/scripts/addons/Modeling-Cloth-master/ModelingCloth.py", line 921, in modal
    pos = queryMousePosition()
NameError: name 'queryMousePosition' is not defined

location: <unknown location>:-1
```

Would you know how to fix this?

TIA,

Rob van Wees.

**Comment by the3dadvantage** [comment]
Had to do with changes that were not applied to both raycast functions. Should be fixed now
